export interface GenericTableInterface {
    itemsExceptions?: any[];
    data?: any[];
    onChangePage: (params?: any) => void;
    onDelete?: (params?: any) => void;
    onSearch: (params?: any) => void;
    selectFilter?: boolean;
    selectFilterArray?: any[];
    selectFilterItemKey?: string;
    keyItem?: string;
    readOnly?: boolean;
    singleDelete?: boolean;
    hasDashboardView?: boolean;
    hasManageView?: boolean;
    hasAchivement?: boolean;
    onEdit?: (params?: any) => void;
    mangeLink?: string;
    achivementLink?: string;
    achivementTitle?: string;
    dashboardLink?: string;
    selectFilterItemValue?: string;
    onSelectFilter?: (params: any) => void;
    multipleAssign?: boolean;
    onAssign?: (params: any) => void;
    removeEditButton?: boolean;
    removeUnAssignSelectFiler?: boolean;
    removeSearch?: boolean;
    manageTitle?: string;
    showChange?: boolean;
    onPressShow?: (params: any) => void;
    hasShare?: boolean;
    studentReport?: boolean;
    studentReportLink?: string;
    teacherReport?: boolean;
    teacherReportLink?: string;
    supporterReport?: boolean;
    supporterReportLink?: string;
    changeImage?: boolean;
    uploadImage?: (params: any, params2: any) => void;
    additionalData?: any;

}